### PR TITLE
Update FtpClient.php

### PR DESCRIPTION
**Pull request by tekinnnnn**

### CODE REVIEW

**Comment by tekinnnnn** [comment]
#10

**Comment by AmraniCh** [comment]
Hy, thanks for opening issue #10 and for your PR.

You're right, some FTP servers may not support the SIZE feature especially the old ones, actually, I've don't think about this when I've implemented the `FtpClient::isDir` and `FtpClient::isFile` methods, however, there are few methods to check if an FTP file is a directory type, one is to try to navigate the directory using 'ftp_chdir' function and if it fails then the file is often a regular file or it doesn't exist either, the problem here is that this solution may cause negative side effects, like if fails to return the original directory, also it so slow compared to the SIZE option.

The better solution is to use the `ftp_mlsd`, which is unfortunately available as of  PHP v7.2, that why I've created the [ftp-bridge](https://github.com/lazzard/ftp-bridg) which can be used to implement those FTP functions that aren't available in old PHP versions (still under development).

The only solution we have here is to use `FtpClient::listDirectoryDetails` which uses `ftp_rawlist` to return all files information in a directory including the file type.

Can you please show me the result of the `FtpClient::getFeatures()` returned by your FTP server?

**Comment by tekinnnnn** [comment]
Hello,

Here the results : 

resim

**Comment by AmraniCh** [comment]
It seems that your FTP server supports the SIZE command indeed, thus the `FtpClient::isDir` and `FtpClient::isFile` should work for you.

However, in all cases, those methods should first check if the SIZE feature supported I will consider a PR for this.

**Comment by AmraniCh** [comment]
Resolved in #12.

**Pull request closed without merging**
