### PR TITLE
Add const `FTP_FUNCTIONS_PREFIX`

### PR DESCRIPTION
**Pull request by PululuK**
Minor code improvement.

### CODE REVIEW

**Comment by AmraniCh** [comment]
Hey, thanks for opening this PR and contributing to this project.

Sorry, but I cant see the benefit from adding this constant, the `ftp_` prefix used only one time and probably we wont use it anymore, what you say about that ?

**Comment by PululuK** [comment]
> Hey, thanks for opening this PR and contributing to this project.
> 
> Sorry, but I cant see the benefit from adding this constant, the `ftp_` prefix used only one time and probably we wont use it anymore, what you say about that ?

code readability improvement :)

**Comment by AmraniCh** [comment]
Okay, but why use `static` instead of `self` here ?

**Comment by AmraniCh** [comment]
Sorry, I don't see that this PR worth merging, I really appreciate your contribution and your interest to improve this package, thank you!

**Pull request closed without merging**
